### PR TITLE
Adds functionality for multiple maps on a page

### PR DESCRIPTION
**Pull request by jcdm**
Adds the required serialisation of DIVs and related CSS and code and adds snippet and class functionality to allow for specifying a docid to target specific resources in map calls. This is related to #3

### CODE REVIEW

**Comment by jcdm** [comment]
First commit of this size in my coding career - let me know if I've done anything silly (I can take it).

**Comment by jcdm** [comment]
New updates shores up error reporting on the loaded resource. Adding a check for the correct class_key on the loaded resource and including the ID of the failing resource with the new errors.

**Comment by muzzwood** [comment]
Nice work! Looks good. Just wondering if it might be better to set the namespace 'lr.' prefix to the [[+docid]] placeholder since other extras might also use the same thing. What do you think?

**Comment by jcdm** [comment]
Yeah - good thinking. Now done.

**Pull request merged**
