### PR TITLE
Get the location profile values directly

### PR DESCRIPTION
**Pull request by Jako**
With this change all LocationProfile values are added to the Location object, if the toArray method is used or the get method is used with an array in the fieldname.

That way the LocationProfile fields are directly available in a getResources row chunk as placeholder with the prefix `location_`.

### CODE REVIEW

**Comment by muzzwood** [comment]
This is great!
I'll get it tested and merged soon.
Thanks @Jako

**Comment by Jako** [comment]
Maybe the values are available directly on the resource itself, too. But I did not check that.

I am not sure about pdoResources, since that bypasses the default modResource object methods.

**Comment by Jako** [comment]
There was a bug in the current code that created an issue in the JSON response, that is sent during a resource update.

**Comment by muzzwood** [comment]
Thanks @Jako . Works beautifully!

**Pull request merged**
